---
title: "Two parameter logistic item response model"
author: "서용덕"
date: "`r Sys.Date()`"
output: html_document
---

Original source code from:
https://mc-stan.org/users/documentation/case-studies/tutorial_twopl.html


```{r}
library(rstan)
rstan_options(auto_write=TRUE)
rstan_options(threads_per_chain=1)
options(mc.cores = parallel::detectCores())

library(reshape2)
library(ggplot2)
library(gridExtra)

library(devtools)
library(edstan)
```

## 1. Introduction

```{r}
preview_rows <- seq(from=1, to=nrow(spelling), length=10)
spelling[preview_rows, ]
```

```{r}
# Record existing plot presets and prepare to make side-by-side pots
par_bkp <- par(no.readonly = TRUE)
par(mfrow = c(1, 2))

# Left plot
person_scores <- apply(spelling[, 2:5], 1, sum)
person_counts <- table(person_scores)
barplot(person_counts, main = "Raw score distribution", xlab = "Raw score", 
    ylab = "Number of persons")

# Right plot
item_scores <- apply(spelling[, 2:5], 2, mean)
barplot(item_scores, main = "Proportion correct by item", ylab = "Proportion correct", 
    ylim = c(0, 1), xaxt = "n")
# x-axis with angled labels
text(x = 0.85 + (1:length(item_scores) - 1) * 1.2, y = -0.05, labels = names(item_scores), 
    xpd = TRUE, srt = 30, pos = 2)

# Return to previous plot presets
par(par_bkp)
```

```{r}
# Load packages
library(rstan)
library(edstan)

# Make the data list
data_dich <- irt_data(y = aggression$dich, 
                      ii = labelled_integer(aggression$description), 
                      jj = aggression$person)

# Fit the Rasch model
fit_rasch <- irt_stan(data_dich, model = "rasch_latent_reg.stan",
                      iter = 200, chains = 4)

# View convergence statistics
rhat_columns(fit_rasch)

# View summary of parameter posteriors					  
print_irt_stan(fit_rasch, data_dich)

# Add a latent regression to the previous model
data_lr <- irt_data(y = aggression$dich, 
                    ii = labelled_integer(aggression$description), 
                    jj = aggression$person,
                    covariates = aggression[, c("male", "anger")],
                    formula = ~ 1 + male*aggression)
fit_lr <- irt_stan(data_lr, model = "rasch_latent_reg.stan",
                   iter = 200, chains = 4)
```


```{r}
X <- spelling[, 2:5]  # Response matrix
W <- cbind(1, spelling[, 1])  # Person covariate matrix
spelling_list <- irt_data(response_matrix = X)

# Fit 2PL to the data using irt_stan()
twopl_fit <- irt_stan(spelling_list, model = "2pl_latent_reg.stan", iter = 200, 
    chains = 4)

# View summary of posteriors using print_irt_stan()
print_irt_stan(twopl_fit, spelling_list)

# Alternatively:
# print(twopl_fit, pars = c("alpha", "beta", "lambda"))
```
